version: '3'

services:
  mongo:
    image: mongo:7.0.4
    ports:
      - "27017:27017"
    volumes:
      - ./services/mongo-data:/data/db
    # user: 1000:1000

  rabbitmq:
    image: rabbitmq:3.12.11-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./services/rabbitmq-data:/var/lib/rabbitmq

  # kong:
  #   image: kong/kong-gateway:3.4.3.2
  #   environment:
  #     KONG_PROXY_LISTEN: 0.0.0.0:8000
  #     KONG_ADMIN_LISTEN: 0.0.0.0:8001
  #   ports:
  #     - "8000:8000"
  #     - "8001:8001"
  #   volumes:
  #     - ./services/kong-data:/usr/local/kong/declarative


